global:  
  scrape_interval: 60s  
  evaluation_interval: 60s  
  
scrape_configs:  
  - job_name: 'postgres'  
    static_configs:  
      - targets: ['postgres-exporter:9187']  
        labels:  
          project: 'default'  
          environment: 'self-hosted'
  - job_name: 'node'  
    static_configs:  
      - targets: ['node-exporter:9100']  
        labels:  
          environment: 'self-hosted'  
          project: 'default'