apiVersion: 1  
contactPoints:  
  - orgId: 1  
    name: realtime-broadcast  
    receivers:  
      - uid: realtime-webhook  
        type: webhook  
        settings:  
          url: http://realtime:4000/api/broadcast  
          httpMethod: POST  
          authorization_scheme: Bearer  
          authorization_credentials: ${SERVICE_ROLE_KEY}  
          extraHeaders:  
            Host: realtime-dev.realtime